services:
  db:
    image: postgres:15
    container_name: postgres-db
    restart: always
    env_file:
    - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    container_name: django-app
    image: xedose/blogging-app
    command: >
      sh -c "
      until nc -z db 5432; do
        echo 'Waiting for postgres...';
        sleep 2;
      done;
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000
      "
    volumes:
      - ./app:/usr/src/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

volumes:
  postgres_data: