apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-db
  namespace: blog
spec:
  serviceName: "db-service"
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: postgres
        image: postgres:15
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data # This is the "Base Dir" for Postgres internally
        # env from ConfigMap 
        envFrom:
        - configMapRef:
            name: postgres-config
        # env from Secret
        - secretRef:
            name: postgres-secret
        
        readinessProbe:
          exec:
            command: ["pg_isready", "-U", "postgres"]
          initialDelaySeconds: 10
          periodSeconds: 5

        livenessProbe:
          exec:
            command: ["pg_isready", "-U", "postgres"]
          initialDelaySeconds: 20
          periodSeconds: 10
        
        resources:
        requests:
          cpu: "250m"
          memory: "256Mi"
        limits:
          cpu: "500m"
          memory: "512"

      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-pvc
