apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: blog
data:
  POSTGRES_DB: "postgres"
  POSTGRES_USER: "postgres"

---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: blog
type: Opaque
data:
  POSTGRES_PASSWORD: "UG9zdGdyZXNAMTIz"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: blog

spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 300Mi

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-db
  namespace: blog
spec:
  serviceName: "db-service"
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: postgres
        image: postgres:15
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data # This is the "Base Dir" for Postgres internally
        # env from ConfigMap 
        envFrom:
        - configMapRef:
            name: postgres-config
        # env from Secret
        - secretRef:
            name: postgres-secret
        
        readinessProbe:
          exec:
            command: ["pg_isready", "-U", "postgres"]
          initialDelaySeconds: 10
          periodSeconds: 5

        livenessProbe:
          exec:
            command: ["pg_isready", "-U", "postgres"]
          initialDelaySeconds: 20
          periodSeconds: 10
        
        resources:
          requests:
            cpu: "250m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"

      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: blog
spec:
  selector:
    app: postgres
  ports:
  - port: 5432
    targetPort: 5432
