name: Push-to-EC2

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:
    name: Push to EC2 Instance
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4.1.7
        
      - name: Deploy to my EC2 instance
        uses: easingthemes/ssh-deploy@v5.0.3
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          SOURCE: "./"
          REMOTE_HOST: "ec2-65-0-134-6.ap-south-1.compute.amazonaws.com"
          REMOTE_USER: "ubuntu"
          TARGET: "/home/ubuntu/blogging-app

workflow_dispatch:
